#!/bin/bash
set -e

# Обновляем список пакетов и устанавливаем зависимости
sudo apt update && sudo apt install -y build-essential pkg-config libssl-dev protobuf-compiler

# Устанавливаем Rust с автоматическим подтверждением стандартных опций
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
. "$HOME/.cargo/env"

# Добавляем целевой триплет riscv32i
rustup target add riscv32i-unknown-none-elf

# Устанавливаем Nexus CLI, автоматически подтверждая условия использования
echo y | curl https://cli.nexus.xyz/ | sh

# Запускаем ноду в новой screen-сессии с именем "nexus"
# Команда внутри screen запускает ноду и оставляет сессию открытой
screen -S nexus -dm bash -c "/root/.nexus/network-api/clients/cli/target/release/nexus-network run; exec bash"
# Подключаемся к сессии, чтобы оставаться в ней
screen -r nexus
