#!/usr/bin/env bash

set -e

# Цвета для вывода
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

echo -e "${GREEN}Начинаем установку Docker...${NC}"

# Обновляем систему и устанавливаем зависимости для Docker
sudo apt update -y
sudo apt upgrade -y
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common

# Добавляем официальный ключ Docker
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# Добавляем репозиторий Docker
echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
 https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
 sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Устанавливаем Docker
sudo apt update -y
sudo apt install -y docker-ce docker-ce-cli containerd.io

# Запускаем и включаем Docker
sudo systemctl start docker
sudo systemctl enable docker

echo -e "${GREEN}Docker установлен успешно!${NC}"

# Устанавливаем Docker Compose
echo -e "${GREEN}Устанавливаем Docker Compose...${NC}"
DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')
sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# Проверяем установку Docker Compose
docker-compose --version

echo -e "${GREEN}Docker Compose установлен успешно!${NC}"

# Установка node_exporter для мониторинга
echo -e "${GREEN}Устанавливаем node_exporter...${NC}"

# Проверка наличия curl и установка, если не установлен
if ! command -v curl &> /dev/null; then
    sudo apt update
    sudo apt install curl -y
fi
sleep 1

# Скачиваем и устанавливаем node_exporter
cd $HOME && \
wget https://github.com/prometheus/node_exporter/releases/download/v1.2.0/node_exporter-1.2.0.linux-amd64.tar.gz
tar xvf node_exporter-1.2.0.linux-amd64.tar.gz
rm node_exporter-1.2.0.linux-amd64.tar.gz
sudo mv node_exporter-1.2.0.linux-amd64 node_exporter
chmod +x $HOME/node_exporter/node_exporter
sudo mv $HOME/node_exporter/node_exporter /usr/bin/
rm -Rvf $HOME/node_exporter/

# Создаем systemd-сервис для exporterd
sudo tee /etc/systemd/system/exporterd.service > /dev/null <<EOF
[Unit]
Description=node_exporter
After=network-online.target
[Service]
User=$USER
ExecStart=/usr/bin/node_exporter
Restart=always
RestartSec=3
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF

# Запускаем сервис exporterd
sudo systemctl daemon-reload
sudo systemctl enable exporterd
sudo systemctl restart exporterd

# Открываем порт 9100 для node_exporter
sudo ufw allow 9100

echo -e "${GREEN}node_exporter установлен и запущен!${NC}"

echo -e "${GREEN}Все операции завершены успешно!${NC}"
