#!/bin/bash

# Имя контейнера
container_name="Sonaric"

# Образ Docker
image_version="ubuntu:22.04"

# Функция для проверки доступности порта
check_port() {
  local port=$1
  if lsof -i:"$port" >/dev/null 2>&1; then
    return 1 # Порт занят
  else
    return 0 # Порт свободен
  fi
}

# Определение свободного порта, начиная с 8080
container_port=8080
while ! check_port "$container_port"; do
  echo "Порт $container_port уже занят. Проверяем следующий..."
  container_port=$((container_port + 1))
done

echo "Выбран порт: $container_port"

# Проверка, существует ли контейнер с таким именем
if [ $(docker ps -a -q -f name="^${container_name}$") ]; then
  echo "Контейнер с именем $container_name уже существует. Удаляем его..."
  docker stop $container_name >/dev/null 2>&1
  docker rm $container_name >/dev/null 2>&1
  echo "Контейнер $container_name удалён."
fi

# Создание и запуск контейнера
echo "Создаем и запускаем контейнер..."
docker run -it --name $container_name -p $container_port:$container_port \
  -e TERM=xterm $image_version sh -c "$(curl -fsSL https://get.sonaric.xyz/scripts/install.sh)"

# Проверка запуска контейнера
if [ $? -eq 0 ]; then
  echo "Контейнер $container_name успешно создан и запущен на порту $container_port."
else
  echo "Произошла ошибка при создании или запуске контейнера. Проверьте настройки."
  exit 1
fi

# Завершение работы скрипта
echo "Контейнер $container_name запущен. Вы можете работать в нём."
